import {
  render,
  screen,
  fireEvent,
  waitFor,
  waitForElementToBeRemoved,
  within,
  getByRole,
  getByLabelText,
  getByPlaceholderText,
  getByText,
  getByTestId,
  getAllByRole,
  getAllByLabelText,
  getAllByPlaceholderText,
  getAllByText,
  getAllByTestId,
  queryByRole,
  queryByLabelText,
  queryByPlaceholderText,
  queryByText,
  queryByTestId,
  queryAllByRole,
  queryAllByLabelText,
  queryAllByPlaceholderText,
  queryAllByText,
  queryAllByTestId,
  findByRole,
  findByLabelText,
  findByPlaceholderText,
  findByText,
  findByTestId,
  findAllByRole,
  findAllByLabelText,
  findAllByPlaceholderText,
  findAllByText,
  findAllByTestId,
  renderHook,
  act,
  cleanup
} from '@testing-library/react';
import * as react from 'react';

export {react};

// Export specific testing library functions
export {
  render,
  screen,
  fireEvent,
  waitFor,
  waitForElementToBeRemoved,
  within,
  getByRole,
  getByLabelText,
  getByPlaceholderText,
  getByText,
  getByTestId,
  getAllByRole,
  getAllByLabelText,
  getAllByPlaceholderText,
  getAllByText,
  getAllByTestId,
  queryByRole,
  queryByLabelText,
  queryByPlaceholderText,
  queryByText,
  queryByTestId,
  queryAllByRole,
  queryAllByLabelText,
  queryAllByPlaceholderText,
  queryAllByText,
  queryAllByTestId,
  findByRole,
  findByLabelText,
  findByPlaceholderText,
  findByText,
  findByTestId,
  findAllByRole,
  findAllByLabelText,
  findAllByPlaceholderText,
  findAllByText,
  findAllByTestId,
  renderHook,
  act,
  cleanup
};